export interface SnakeTileData {
  tile: number
  title: string
  category: string
  hex_code: string
  point_1: string
  point_2: string
  point_3: string
}

export const SNAKE_LADDER_TILES: SnakeTileData[] = [
  { tile: 1, title: 'Team Cheer', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Gather team', point_2: 'Shout cheer', point_3: 'Loud energy' },
  { tile: 2, title: 'Quick Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +2', point_2: 'Gain 200 points', point_3: 'Continue' },
  { tile: 3, title: 'Blue Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find blue item', point_2: 'Show it', point_3: 'Return' },
  { tile: 4, title: 'Jumping Jacks', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All perform 3', point_2: 'Sync together', point_3: 'Finish' },
  { tile: 5, title: 'Chapteh 2', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '2 passes', point_2: 'No drop', point_3: 'Team effort' },
  { tile: 6, title: 'Object Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find any object', point_2: 'Show facilitator', point_3: 'Return' },
  { tile: 7, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '3 push-ups', point_2: 'Proper form', point_3: 'Count aloud' },
  { tile: 8, title: 'Bonus Boost', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +3', point_2: 'Gain 300', point_3: 'Continue' },
  { tile: 9, title: 'Balance Hold', category: 'Physical', hex_code: '#FFCCB6', point_1: 'One leg', point_2: '5 seconds', point_3: 'All succeed' },
  { tile: 10, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '1 player scores', point_2: 'One attempt', point_3: 'Success' },
  { tile: 11, title: 'Watch Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find watch wearer', point_2: 'High-five', point_3: 'Return' },
  { tile: 12, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: '5 reps', point_2: 'Full depth', point_3: 'Count' },
  { tile: 13, title: 'Finger Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 3 cups', point_2: 'One finger', point_3: 'Hold' },
  { tile: 14, title: 'Bonus Points', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Gain 200', point_2: 'No move', point_3: 'Continue' },
  { tile: 15, title: 'Group Pose', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Funny pose', point_2: 'Take photo', point_3: 'Show' },
  { tile: 16, title: 'Red Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find red item', point_2: 'Show', point_3: 'Return' },
  { tile: 17, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '5 reps', point_2: 'Controlled', point_3: 'Finish' },
  { tile: 18, title: 'Stack 4', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 4 cups', point_2: 'One finger', point_3: 'Hold' },
  { tile: 19, title: 'Glasses Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find glasses wearer', point_2: 'Point', point_3: 'Return' },
  { tile: 20, title: 'Forward Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +3', point_2: 'Gain 200', point_3: 'Continue' },
  { tile: 21, title: 'Team Chant', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Group chant', point_2: 'Loud', point_3: 'Together' },
  { tile: 22, title: 'White Shoes', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 2 people', point_2: 'White shoes', point_3: 'Photo' },
  { tile: 23, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '5 reps', point_2: 'Proper form', point_3: 'Count' },
  { tile: 24, title: 'Stack 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 5 cups', point_2: 'One finger', point_3: 'Hold' },
  { tile: 25, title: 'Choice +1/-1', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Help +1', point_2: 'OR disrupt -1', point_3: 'OR skip' },
  { tile: 26, title: 'Cup Toss 2', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '2 scores needed', point_2: 'Team effort', point_3: 'One try' },
  { tile: 27, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '10 reps', point_2: 'Controlled', point_3: 'Finish' },
  { tile: 28, title: 'Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Gain 300', point_2: 'No move', point_3: 'Continue' },
  { tile: 29, title: 'Stack Control', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Steady stack', point_2: 'Hold 3s', point_3: 'No drop' },
  { tile: 30, title: 'Plank', category: 'Physical', hex_code: '#FFCCB6', point_1: '10 sec', point_2: 'All', point_3: 'No drop' },
  { tile: 31, title: 'Chapteh 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '5 passes', point_2: 'Max', point_3: 'No drop' },
  { tile: 32, title: 'Help Tile', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose team', point_2: 'Move +2', point_3: 'Announce' },
  { tile: 33, title: 'Hat Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find hat wearer', point_2: 'Point', point_3: 'Return' },
  { tile: 34, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: '8 reps', point_2: 'Full depth', point_3: 'Count' },
  { tile: 35, title: 'Stack Balance', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack stable', point_2: 'Hold', point_3: 'No drop' },
  { tile: 36, title: 'Go Back', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Move -3', point_2: 'No points', point_3: 'Continue' },
  { tile: 37, title: 'Item Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find item', point_2: 'Show', point_3: 'Return' },
  { tile: 38, title: 'Chapteh Clap', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '3 passes', point_2: 'Clap', point_3: 'No drop' },
  { tile: 39, title: 'Big Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Gain 400', point_2: 'No move', point_3: 'Continue' },
  { tile: 40, title: 'AI Pose', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Create pose', point_2: 'Photo', point_3: 'Show' },
  { tile: 41, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '8 reps', point_2: 'Proper form', point_3: 'Count' },
  { tile: 42, title: 'Stack 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 5 cups', point_2: 'One finger', point_3: 'Hold' },
  { tile: 43, title: 'Group Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 3 people', point_2: 'Photo', point_3: 'Show' },
  { tile: 44, title: 'Choice +2/-2', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Help +2', point_2: 'OR disrupt -2', point_3: 'OR skip' },
  { tile: 45, title: 'Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move -4', point_2: 'Lose 200', point_3: 'Continue' },
  { tile: 46, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '3 scores', point_2: 'Team', point_3: 'One try' },
  { tile: 47, title: 'Chapteh Rotate', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '4 passes', point_2: 'No repeat', point_3: 'No drop' },
  { tile: 48, title: 'Stack 6', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 6 cups', point_2: 'One finger', point_3: 'Hold' },
  { tile: 49, title: 'Photo Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Take photo', point_2: 'Show', point_3: 'Return' },
  { tile: 50, title: 'Swap Tile', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose team', point_2: 'Swap position', point_3: 'Announce' },
  { tile: 51, title: 'Plank', category: 'Physical', hex_code: '#FFCCB6', point_1: '15 sec', point_2: 'All', point_3: 'No drop' },
  { tile: 52, title: 'Bonus Move', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +5', point_2: 'Gain 400', point_3: 'Continue' },
  { tile: 53, title: 'Cup Toss Half', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Half team scores', point_2: 'Round up', point_3: 'One try' },
  { tile: 54, title: 'Blue Shirt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find blue shirt', point_2: 'High-five', point_3: 'Return' },
  { tile: 55, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: '10 reps', point_2: 'Full depth', point_3: 'Count' },
  { tile: 56, title: 'Go Back', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Move -5', point_2: 'No points', point_3: 'Continue' },
  { tile: 57, title: 'Silent Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'No talking', point_2: 'Stack 5', point_3: 'Hold' },
  { tile: 58, title: 'Chapteh 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '5 passes', point_2: 'No drop', point_3: 'Team' },
  { tile: 59, title: 'Choice Split', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Help 2 teams +1', point_2: 'OR disrupt -2', point_3: 'Choose' },
  { tile: 60, title: 'Forward Move', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +5', point_2: 'Continue', point_3: 'No points' },
  { tile: 61, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '10 reps', point_2: 'Proper form', point_3: 'Count' },
  { tile: 62, title: 'Speed Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 6', point_2: '10 sec', point_3: 'One finger' },
  { tile: 63, title: 'Group Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 5 people', point_2: 'Photo', point_3: 'Show' },
  { tile: 64, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '15 reps', point_2: 'Controlled', point_3: 'Finish' },
  { tile: 65, title: 'Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move -6', point_2: 'Lose 300', point_3: 'Continue' },
  { tile: 66, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '3 players score', point_2: 'One try', point_3: 'Count' },
  { tile: 67, title: 'Chapteh Circle', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '4 passes', point_2: 'Spread', point_3: 'No drop' },
  { tile: 68, title: 'Choice Tactical', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Help behind +2', point_2: 'OR hit leader -2', point_3: 'Decide' },
  { tile: 69, title: 'Stack 7', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 7 cups', point_2: 'One finger', point_3: 'Hold' },
  { tile: 70, title: 'Freeze', category: 'Physical', hex_code: '#FFCCB6', point_1: 'Hold pose', point_2: '10 sec', point_3: 'All' },
  { tile: 71, title: 'Plank', category: 'Physical', hex_code: '#FFCCB6', point_1: '20 sec', point_2: 'All', point_3: 'No drop' },
  { tile: 72, title: 'Big Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +6', point_2: 'Gain 700', point_3: 'Continue' },
  { tile: 73, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '4 scores', point_2: 'Team', point_3: 'One try' },
  { tile: 74, title: 'Match Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 2 same colour', point_2: 'Photo', point_3: 'Show' },
  { tile: 75, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: '12 reps', point_2: 'Full depth', point_3: 'Count' },
  { tile: 76, title: 'Go Back', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Move -7', point_2: 'No points', point_3: 'Continue' },
  { tile: 77, title: 'Leader Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Leader talks', point_2: 'Stack 6', point_3: 'One finger' },
  { tile: 78, title: 'Chapteh All', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '5 passes', point_2: 'All touch', point_3: 'No drop' },
  { tile: 79, title: 'Chaos Tile', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Move team -5', point_2: 'Steal 300', point_3: 'Choose' },
  { tile: 80, title: 'Forward', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +6', point_2: 'Continue', point_3: 'No points' },
  { tile: 81, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '12 reps', point_2: 'Proper form', point_3: 'Count' },
  { tile: 82, title: 'Silent Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'No talking', point_2: 'Stack 7', point_3: 'Hold' },
  { tile: 83, title: 'Group Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 6 people', point_2: 'Photo', point_3: 'Show' },
  { tile: 84, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: '20 reps', point_2: 'Controlled', point_3: 'Finish' },
  { tile: 85, title: 'Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move -8', point_2: 'Lose 500', point_3: 'Continue' },
  { tile: 86, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '4 players score', point_2: 'One try', point_3: 'Count' },
  { tile: 87, title: 'Chapteh Clap', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '5 passes', point_2: 'Clap', point_3: 'No drop' },
  { tile: 88, title: 'Photo Task', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Take creative photo', point_2: 'Show', point_3: 'Return' },
  { tile: 89, title: 'Stack 8', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 8 cups', point_2: 'One finger', point_3: 'Hold' },
  { tile: 90, title: 'Swap Leader', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Swap leader', point_2: 'Change position', point_3: 'Announce' },
  { tile: 91, title: 'Choice Final', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Help +3', point_2: 'OR disrupt -3', point_3: 'OR skip' },
  { tile: 92, title: 'Mega Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move +8', point_2: 'Gain 1000', point_3: 'Continue' },
  { tile: 93, title: 'Exact Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Exactly 2 score', point_2: 'No more', point_3: 'One try' },
  { tile: 94, title: 'Item Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 3 items', point_2: 'Show', point_3: 'Return' },
  { tile: 95, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: '15 reps', point_2: 'Full depth', point_3: 'Count' },
  { tile: 96, title: 'Big Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move -10', point_2: 'Lose 800', point_3: 'Continue' },
  { tile: 97, title: 'Weak Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Weak hand', point_2: 'Stack 7', point_3: 'Hold' },
  { tile: 98, title: 'Silent Chapteh', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: '5 passes', point_2: 'No talking', point_3: 'No drop' },
  { tile: 99, title: 'Final Challenge', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose task', point_2: 'Complete', point_3: 'Get approval' },
  { tile: 100, title: 'Congratulations!', category: 'Celebration', hex_code: '#FFD700', point_1: 'You made it!', point_2: 'Celebrate together', point_3: 'Champions!' },
]
