export interface SnakeTileData {
  tile: number
  title: string
  category: string
  hex_code: string
  point_1: string
  point_2: string
  point_3: string
}

export const SNAKE_LADDER_TILES: SnakeTileData[] = [
  { tile: 1, title: 'Team Cheer', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Gather all team members together', point_2: 'Agree on a short team cheer', point_3: 'Shout it loudly together' },
  { tile: 2, title: 'Quick Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move your team piece forward by 2 tiles', point_2: 'Add 200 points to your score', point_3: 'No task required' },
  { tile: 3, title: 'Blue Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Look around for any blue object', point_2: 'Take a photo or point it out clearly', point_3: 'Show facilitator for approval' },
  { tile: 4, title: 'Jumping Jacks', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All team members perform 3 jumping jacks', point_2: 'Move in sync if possible', point_3: 'Finish at the same time' },
  { tile: 5, title: 'Chapteh 2', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 2 successful kicks in total', point_2: 'Ball must not drop to the ground', point_3: 'Any team member can kick' },
  { tile: 6, title: 'Object Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find any random object nearby', point_2: 'Bring it or point it out clearly', point_3: 'Show facilitator' },
  { tile: 7, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 3 push-ups', point_2: 'Maintain proper form', point_3: 'Count out loud together' },
  { tile: 8, title: 'Bonus Boost', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move forward by 3 tiles', point_2: 'Gain 300 points', point_3: 'Continue game immediately' },
  { tile: 9, title: 'Balance Hold', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members stand on one leg', point_2: 'Hold for 5 seconds', point_3: 'No one should lose balance' },
  { tile: 10, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one attempt', point_2: 'At least 1 ball must land in a cup', point_3: 'Count only successful shots' },
  { tile: 11, title: 'Watch Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find someone wearing a watch', point_2: 'Approach politely', point_3: 'Give them a high-five' },
  { tile: 12, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 5 squats', point_2: 'Go to full depth', point_3: 'Count together' },
  { tile: 13, title: 'Finger Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member uses only 1 finger', point_2: 'Stack 3 cups together', point_3: 'Hold structure for 2 seconds' },
  { tile: 14, title: 'Bonus Points', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Gain 200 points', point_2: 'No movement required', point_3: 'Continue game' },
  { tile: 15, title: 'Group Pose', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Create a funny team pose', point_2: 'Take a group photo', point_3: 'Show facilitator' },
  { tile: 16, title: 'Red Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find any red object nearby', point_2: 'Take photo or point it out', point_3: 'Get approval' },
  { tile: 17, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 5 sit-ups', point_2: 'Move in controlled manner', point_3: 'Finish together' },
  { tile: 18, title: 'Stack 4', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Use only one finger each', point_2: 'Stack 4 cups into a tower', point_3: 'Hold steady for 2 seconds' },
  { tile: 19, title: 'Glasses Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find someone wearing glasses', point_2: 'Point them out clearly', point_3: 'Return to your spot' },
  { tile: 20, title: 'Forward Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move forward 3 tiles', point_2: 'Gain 200 points', point_3: 'Continue playing' },
  { tile: 21, title: 'Team Chant', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Gather team together', point_2: 'Create a short chant', point_3: 'Perform loudly as a group' },
  { tile: 22, title: 'White Shoes', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 2 people wearing white shoes', point_2: 'Take a group photo with them', point_3: 'Show facilitator' },
  { tile: 23, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 5 push-ups', point_2: 'Keep proper form', point_3: 'Count aloud together' },
  { tile: 24, title: 'Stack 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Use one finger per person', point_2: 'Stack 5 cups into a tower', point_3: 'Hold for 2 seconds' },
  { tile: 25, title: 'Choice +1/-1', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose another team', point_2: 'Either move them forward 1 tile OR backward 1 tile', point_3: 'Or choose to skip action' },
  { tile: 26, title: 'Cup Toss 2', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one throw', point_2: 'Achieve at least 2 successful shots total', point_3: 'Count only valid shots' },
  { tile: 27, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 10 sit-ups', point_2: 'Maintain control', point_3: 'Finish together' },
  { tile: 28, title: 'Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Gain 300 points', point_2: 'No movement required', point_3: 'Continue game' },
  { tile: 29, title: 'Stack Control', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 5 cups using one finger each', point_2: 'Keep structure stable', point_3: 'Hold for 3 seconds' },
  { tile: 30, title: 'Plank', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members hold plank position', point_2: 'Hold for 10 seconds', point_3: 'No one drops early' },
  { tile: 31, title: 'Chapteh 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 5 successful passes', point_2: 'Do not let chapteh drop', point_3: 'Any team member can kick' },
  { tile: 32, title: 'Help Tile', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose any team', point_2: 'Move them forward by 2 tiles', point_3: 'Announce clearly' },
  { tile: 33, title: 'Hat Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find someone wearing a hat', point_2: 'Point them out', point_3: 'Return to your group' },
  { tile: 34, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 8 squats', point_2: 'Go to full depth', point_3: 'Count together' },
  { tile: 35, title: 'Stack Balance', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack cups carefully', point_2: 'Keep them steady', point_3: 'Hold for 3 seconds' },
  { tile: 36, title: 'Go Back', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Move your team piece backward 3 tiles', point_2: 'No points affected', point_3: 'Continue game' },
  { tile: 37, title: 'Item Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find any object nearby', point_2: 'Bring or point it out', point_3: 'Show facilitator' },
  { tile: 38, title: 'Chapteh Clap', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 3 passes', point_2: 'Clap once between each kick', point_3: 'Do not drop' },
  { tile: 39, title: 'Big Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Gain 400 points', point_2: 'No movement required', point_3: 'Continue game' },
  { tile: 40, title: 'AI Pose', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Create a creative pose as a team', point_2: 'Take a photo', point_3: 'Show facilitator' },
  { tile: 41, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 8 push-ups', point_2: 'Keep proper body alignment', point_3: 'Count together' },
  { tile: 42, title: 'Stack 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Use one finger per person', point_2: 'Build a 5-cup stack', point_3: 'Hold for 2 seconds' },
  { tile: 43, title: 'Group Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 3 people nearby', point_2: 'Take a group photo with them', point_3: 'Show facilitator' },
  { tile: 44, title: 'Choice +2/-2', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose any team', point_2: 'Move them forward 2 OR backward 2', point_3: 'Or choose to skip' },
  { tile: 45, title: 'Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move your piece back 4 tiles', point_2: 'Deduct 200 points', point_3: 'Continue play' },
  { tile: 46, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one attempt', point_2: 'Achieve 3 successful shots total', point_3: 'Count only clean landings' },
  { tile: 47, title: 'Chapteh Rotate', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 4 passes', point_2: 'Each pass by a different person', point_3: 'Do not drop' },
  { tile: 48, title: 'Stack 6', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Use one finger each', point_2: 'Stack 6 cups', point_3: 'Hold for 2 seconds' },
  { tile: 49, title: 'Photo Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Take a creative team photo', point_2: 'Include surroundings', point_3: 'Show facilitator' },
  { tile: 50, title: 'Swap Tile', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose another team', point_2: 'Swap board positions', point_3: 'Announce clearly' },
  { tile: 51, title: 'Plank', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members hold plank', point_2: 'Hold for 15 seconds', point_3: 'No one drops early' },
  { tile: 52, title: 'Bonus Move', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move forward 5 tiles', point_2: 'Gain 400 points', point_3: 'Continue play' },
  { tile: 53, title: 'Cup Toss Half', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one throw', point_2: 'At least half the team must score (round up)', point_3: 'Count successes' },
  { tile: 54, title: 'Blue Shirt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find a person wearing a blue shirt', point_2: 'Approach politely', point_3: 'Give a high-five' },
  { tile: 55, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 10 squats', point_2: 'Full range of motion', point_3: 'Count together' },
  { tile: 56, title: 'Go Back', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Move your piece back 5 tiles', point_2: 'No point change', point_3: 'Continue play' },
  { tile: 57, title: 'Silent Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'No talking allowed', point_2: 'Stack 5 cups using one finger each', point_3: 'Hold for 2 seconds' },
  { tile: 58, title: 'Chapteh 5', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 5 passes total', point_2: 'Do not let it drop', point_3: 'Any member may kick' },
  { tile: 59, title: 'Choice Split', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose two teams to move +1 each', point_2: 'OR choose one team to move -2', point_3: 'Announce decision' },
  { tile: 60, title: 'Forward Move', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move forward 5 tiles', point_2: 'No points awarded', point_3: 'Continue play' },
  { tile: 61, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 10 push-ups', point_2: 'Keep proper form', point_3: 'Count together' },
  { tile: 62, title: 'Speed Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Stack 6 cups using one finger each', point_2: 'Complete within 10 seconds', point_3: 'Hold for 1 second' },
  { tile: 63, title: 'Group Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 5 people nearby', point_2: 'Take a group photo', point_3: 'Show facilitator' },
  { tile: 64, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 15 sit-ups', point_2: 'Controlled movement', point_3: 'Finish together' },
  { tile: 65, title: 'Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move back 6 tiles', point_2: 'Lose 300 points', point_3: 'Continue play' },
  { tile: 66, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one attempt', point_2: 'At least 3 different players must score', point_3: 'Count valid shots' },
  { tile: 67, title: 'Chapteh Circle', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Form a small circle', point_2: 'Perform 4 passes', point_3: 'Do not drop' },
  { tile: 68, title: 'Choice Tactical', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Help a team behind you move +2', point_2: 'OR move the leading team -2', point_3: 'Decide quickly' },
  { tile: 69, title: 'Stack 7', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Use one finger each', point_2: 'Stack 7 cups', point_3: 'Hold for 2 seconds' },
  { tile: 70, title: 'Freeze', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members freeze in a pose', point_2: 'Hold for 10 seconds', point_3: 'No movement allowed' },
  { tile: 71, title: 'Plank', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members hold plank', point_2: 'Hold for 20 seconds', point_3: 'No one drops early' },
  { tile: 72, title: 'Big Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move forward 6 tiles', point_2: 'Gain 700 points', point_3: 'Continue play' },
  { tile: 73, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one throw', point_2: 'Achieve 4 successful shots total', point_3: 'Count successes' },
  { tile: 74, title: 'Match Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 2 people wearing similar colours', point_2: 'Take a photo with them', point_3: 'Show facilitator' },
  { tile: 75, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 12 squats', point_2: 'Full depth', point_3: 'Count together' },
  { tile: 76, title: 'Go Back', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Move your piece back 7 tiles', point_2: 'No points affected', point_3: 'Continue play' },
  { tile: 77, title: 'Leader Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Assign one leader to speak', point_2: 'Stack 6 cups using one finger each', point_3: 'Hold for 2 seconds' },
  { tile: 78, title: 'Chapteh All', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 5 passes', point_2: 'Every member must touch at least once', point_3: 'Do not drop' },
  { tile: 79, title: 'Chaos Tile', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose any team', point_2: 'Move them back 5 tiles', point_3: 'Steal 300 points' },
  { tile: 80, title: 'Forward', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move forward 6 tiles', point_2: 'No points awarded', point_3: 'Continue play' },
  { tile: 81, title: 'Push-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 12 push-ups', point_2: 'Proper form', point_3: 'Count together' },
  { tile: 82, title: 'Silent Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'No talking allowed', point_2: 'Stack 7 cups with one finger each', point_3: 'Hold for 2 seconds' },
  { tile: 83, title: 'Group Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find 6 people nearby', point_2: 'Take a group photo', point_3: 'Show facilitator' },
  { tile: 84, title: 'Sit-Ups', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 20 sit-ups', point_2: 'Controlled movement', point_3: 'Finish together' },
  { tile: 85, title: 'Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move back 8 tiles', point_2: 'Lose 500 points', point_3: 'Continue play' },
  { tile: 86, title: 'Cup Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one attempt', point_2: 'At least 4 different players must score', point_3: 'Count successes' },
  { tile: 87, title: 'Chapteh Clap', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 5 passes', point_2: 'Clap between each kick', point_3: 'Do not drop' },
  { tile: 88, title: 'Photo Task', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Take a cinematic-style team photo', point_2: 'Use environment creatively', point_3: 'Show facilitator' },
  { tile: 89, title: 'Stack 8', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Use one finger each', point_2: 'Stack 8 cups', point_3: 'Hold for 2 seconds' },
  { tile: 90, title: 'Swap Leader', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Swap position with leading team', point_2: 'Confirm with facilitator', point_3: 'Continue play' },
  { tile: 91, title: 'Choice Final', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Help any team move +3', point_2: 'OR move any team -3', point_3: 'OR skip' },
  { tile: 92, title: 'Mega Bonus', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move forward 8 tiles', point_2: 'Gain 1000 points', point_3: 'Continue play' },
  { tile: 93, title: 'Exact Toss', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Each member gets one throw', point_2: 'Exactly 2 successful shots required', point_3: 'Not more, not less' },
  { tile: 94, title: 'Item Hunt', category: 'Hunts', hex_code: '#9AD6D7', point_1: 'Find any 3 different items', point_2: 'Show all to facilitator', point_3: 'Return to play' },
  { tile: 95, title: 'Squats', category: 'Physical', hex_code: '#FFCCB6', point_1: 'All members perform 15 squats', point_2: 'Full depth', point_3: 'Count together' },
  { tile: 96, title: 'Big Penalty', category: 'Bonus', hex_code: '#FF9E41', point_1: 'Move back 10 tiles', point_2: 'Lose 800 points', point_3: 'Continue play' },
  { tile: 97, title: 'Weak Stack', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Use non-dominant hand only', point_2: 'Stack 7 cups', point_3: 'Hold for 2 seconds' },
  { tile: 98, title: 'Silent Chapteh', category: 'Puzzles & Skills', hex_code: '#BD91DA', point_1: 'Perform 5 passes', point_2: 'No talking allowed', point_3: 'Do not drop' },
  { tile: 99, title: 'Final Challenge', category: 'People Skills', hex_code: '#FFE9CD', point_1: 'Choose one: stack 8 cups OR 3 successful cup tosses OR 5 chapteh passes', point_2: 'Complete chosen task fully', point_3: 'Get facilitator approval' },
  { tile: 100, title: 'Congratulations!', category: 'Celebration', hex_code: '#FFD700', point_1: 'You made it!', point_2: 'Celebrate together', point_3: 'Champions!' },
]
